apiVersion: v2
name: magnum
description: A Helm chart for magnum
type: application
version: 1.4.2
appVersion: 22.0.0-12-g5bddad36-4-17
sources:
  - https://github.com/NeCTAR-RC/magnum-helm.git
dependencies:
- name: nectarlib
  version: 4.3.0
  repository: oci://registry.rc.nectar.org.au/nectar-helm
